org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

kotlin.code.style=official
kotlin.mpp.androidSourceSetLayoutVersion=2
kotlin.native.ignoreDisabledTargets=true
kotlin.apple.xcodeCompatibility.nowarn=true

android.useAndroidX=true
android.nonTransitiveRClass=true

# SDK de sockets propio (db-kmp-sdk). Sobreescribir si el clone vive en otra ruta.
ogt.dbKmpSdkPath=/Users/romancanoniero/AndroidStudioProjects/db-kmp-sdk
