server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    absolute_redirect off;

    location = /.well-known/apple-app-site-association {
        default_type application/json;
    }
    location = /.well-known/assetlinks.json {
        default_type application/json;
    }
    location = /apple-app-site-association {
        default_type application/json;
    }
    location /h/ {
        try_files /honor.html =404;
    }
    location /p/ {
        try_files /honor.html =404;
    }
    location /join/ {
        try_files /join.html =404;
    }
    location = /privacy {
        try_files /privacy.html =404;
    }
    location = /privacy.html {
        try_files /privacy.html =404;
    }
    location / {
        try_files $uri $uri/ /index.html;
    }
}
