#!/usr/bin/env python3
"""Genera OgtPetNewsSeed.kt: 100 historias tiernas. sourceUrl solo si hay nota real."""
from pathlib import Path

OUT = Path("/Users/romancanoniero/.cursor/OnlyGoodThings/shared/src/commonMain/kotlin/com/onlygoodthings/shared/data/local/OgtPetNewsSeed.kt")

AUTHORS = [
    "OgtIds.Mariana", "OgtIds.Ana", "OgtIds.Bruno", "OgtIds.Carla", "OgtIds.Lucas",
    "OgtIds.Sofia", "OgtIds.CarlosG", "OgtIds.Camila", "OgtIds.Mateo", "OgtIds.Nicolas",
    "OgtIds.Valeria", "OgtIds.CarlosR", "OgtIds.Lucia", "OgtIds.MateoG", "OgtIds.ValeriaP",
    "OgtIds.Joaquin", "OgtIds.MarianaD", "OgtIds.DiegoF", "OgtIds.Roberto", "OgtIds.Lucas",
]

# (place, hours, tag, photo, body, sourceUrl|None)
STORIES = [
    ("Usaquén, Bogotá", 4, "Adopción", "dog",
     "Medusa, de ocho años y rescatada de maltrato, salió de la Unidad de Cuidado Animal en San Valentín. Nataly y Juan David se enamoraron de su historia y se la llevaron a casa.",
     "https://www.elespectador.com/la-red-zoocial/perros/eligen-a-medusa-una-de-las-perritas-mas-viejas-en-jornada-de-adopcion-en-bogota/"),
    ("Bariloche, Argentina", 9, "Adopción", "dog",
     "Mauro pasó más de un año en Sanidad Animal con leptospirosis y brucelosis. Una voluntaria de Dejando Huellas lo paseaba cada semana y hoy lo adoptó.",
     "https://infobariloche.com.ar/sociedad/bariloche/mauro-el-perro-que-supero-dos-enfermedades-y-finalmente-encontro-una-familia-en-bariloche.html"),
    ("Usaquén, Bogotá", 16, "Adopción", "dog",
     "Pirata Patria, criollo de ocho años, tardó casi dos años en hallar familia después de un rescate grave. Hoy vive con Frank y una nena de cuatro.",
     "https://www.pulzo.com/vivir-bien/mascotas/adopcion-en-bogota-la-emotiva-recuperacion-de-pirata-patria-con-el-idpyba-PP5193405A"),
    ("Winter Park, Florida", 11, "Rescate animal", "puppy",
     "Pilotos voluntarios de Puppy Rescue Flights ya trasladaron más de 12.000 perros y gatos desde refugios saturados hacia hogares en Florida.",
     "https://www.wftv.com/news/local/winter-park-nonprofit-transports-12000-animals-florida-rescues/QBDFXKCZDRBBDPOQ2GV27PIU4E/"),
    ("Iztapalapa, CDMX", 28, "Adopción", "puppy",
     "Cereza y Cerecito, sobrevivientes de la explosión de 2025, cumplieron un año juntos en Huellitas Amor Sin Fronteras.",
     "https://www.milenio.com/comunidad/cereza-cerecito-perritos-sobrevivientes-iztapalapa-regresan-a-hogar"),
    ("Ciudad de México", 22, "Adopción", "dog",
     "CDMX habilitó amaresadoptar.cdmx.gob.mx para dar hogar a perros del Franciscano, Ajusco y la Brigada. El trámite pide visita y contrato de por vida.",
     "https://www.dossierdeprensa.mx/impulsa-brugada-adopcion-responsable-de-animales-rescatados-inicia-proceso-con-plataforma-digital/"),
    ("Cuajimalpa, CDMX", 33, "Adopción", "dog",
     "156 perros volvieron al Franciscano y el Gobierno abrió el canal formal de adopción responsable.",
     "https://www.cronica.com.mx/metropoli/2026/09/14/regresan-156-perros-al-refugio-franciscano-cdmx-inicia-programa-de-adopcion-responsable/"),
    ("Unicentro, Bogotá", 19, "Adopción", "golden",
     "El IDPYBA sigue abriendo jornadas en shoppings y pide casa también para adultos y perros en tratamiento.",
     "https://www.semana.com/4patas/perros/articulo/en-video-la-historia-de-pirata-patria-el-perro-que-fue-rescatado-en-un-estado-de-salud-grave-y-duro-casi-dos-anos-sin-hogar/202625/"),
    # Historias de barrio (sin nota): foto de Commons del tipo de mascota.
    ("Palermo Soho, CABA", 2, "Tránsito animal", "kitten",
     "Luna, gata atigrada de tres meses, pasó la noche en un living de Honduras y Charcas. Mañana busca casa definitiva; come solita y ronronea si le hablás bajo.",
     None),
    ("Villa Crespo, CABA", 5, "Adopción", "cat",
     "Coco llevaba dos semanas en el techo de un taller. Lo bajamos con atún y una sábana. Ya está castrado y duerme en una caja de zapatos.",
     None),
    ("Colegiales, CABA", 7, "Rescate animal", "puppy",
     "Un cachorro mestizo se quedó dormido en la puerta del almacén. Le pusimos Pipo. El vet del barrio le sacó las pulgas y ya mueve la cola si escuchás llaves.",
     None),
    ("Caballito, CABA", 8, "Adopción", "dog",
     "Mora, de siete años, esperaba en el canil del club. Una vecina la pasea a las 7 y a las 19. Buscamos alguien que no le tema a las canas.",
     None),
    ("Almagro, CABA", 10, "Tránsito animal", "rabbit",
     "Nube, coneja blanca, llegó en una caja de verduras. Come heno y se esconde detrás de la heladera. Tres noches de tránsito y ya busca familia calma.",
     None),
    ("Parque Chacabuco, CABA", 12, "Mascotas", "guinea",
     "Dos cuises, Tita y Tito, se quedaron sin casa cuando se mudó el tercer piso. Los tenemos en el balcón tapado. Quien los adopte, se lleva la jaula limpia.",
     None),
    ("Flores, CABA", 13, "Rescate animal", "dog",
     "En la plaza de Rivadavia un pastor mestizo se sentó al lado de la hamaca y no se fue. Lo llamamos Simón. Le dimos agua y ahora espera en el hall del edificio.",
     None),
    ("Boedo, CABA", 15, "Adopción", "tabby",
     "Menta, gata atigrada sorda de un oído, se queda si le hablás de frente. El refugio de Estados Unidos la tiene lista: vacunas al día, busca depto sin perros grandes.",
     None),
    ("San Telmo, CABA", 17, "Tránsito animal", "parrot",
     "Un perico verde se posó en el aljibe de Defensa. Le decimos Loro Pepe. Come manzana y dice «hola» si abrís la ventana. Buscamos criador responsable o vecino con voladera.",
     None),
    ("La Boca, CABA", 18, "Rescate animal", "puppy",
     "Tres cachorros color caramelo aparecieron detrás de la cancha. Ya comieron y duermen amontonados. El sábado hay jornada de castración; hasta entonces, tránsito en Caminito.",
     None),
    ("Belgrano, CABA", 21, "Adopción", "golden",
     "Olivia, golden de diez años, se quedó sin familia por un viaje largo. Camina despacio y se acuesta al sol. No es un perro de corrida: es un perro de siesta.",
     None),
    ("Núñez, CABA", 23, "Mascotas", "turtle",
     "Una tortuga de orejas rojas llegó a la escuela 12 en una palangana. Los chicos le pusieron Rita. El club de ciencias arma un terrario y busca un adulto que la adopte en serio.",
     None),
    ("Saavedra, CABA", 24, "Tránsito animal", "hamster",
     "Pancho, hámster sirio, se escapó del aula y apareció en el guardapolvo de la maestra. Come pipas y duerme de día. Buscamos casa sin gatos curiosos.",
     None),
    ("Chacarita, CABA", 26, "Adopción", "cat",
     "Grisú, gato negro de un solo ojo, vive en la veterinaria de Corrientes. Se sube a las computadoras. Ideal para alguien que trabaje en casa y le guste el silencio.",
     None),
    ("Paternal, CABA", 27, "Rescate animal", "dog",
     "Nala se lastimó una pata en las vías. La operaron en el hospital de campana. Hoy apoya las cuatro y busca un patio chico, no un percherón.",
     None),
    ("Villa Urquiza, CABA", 29, "Adopción", "kitten",
     "Cuatro gatitos naranja nacieron detrás del chino. La mamá ya está castrada. Se van de a uno: el primero se llama Sol y cabe en una taza.",
     None),
    ("Coghlan, CABA", 31, "Mascotas", "chinchilla",
     "Nieve, chinchilla, se quedó sin dueño en un depto de venta. Baño de arena los martes. No es un juguete: es un compañero nocturno que pide calma.",
     None),
    ("Villa Devoto, CABA", 32, "Tránsito animal", "ferret",
     "Kiko, hurón, se metió en un caño de desagüe y salió cubierto de barro. Ya está seco y duerme en una remera. Buscamos alguien que conozca la especie.",
     None),
    ("Versalles, CABA", 34, "Adopción", "donkey",
     "Pancha, burra de 12 años, llegó de un predio de Liniers. Come pasto y se deja cepillar. El club de polo le presta un corral hasta que aparezca un campo chico.",
     None),
    ("Mataderos, CABA", 35, "Rescate animal", "horse",
     "Lucero, caballo flaco, lo bajaron de un carro. Come avena y ya no tiembla. Un vecino del Mercado lo pasea al paso. Buscamos padrinazgo para el fardo.",
     None),
    ("Liniers, CABA", 37, "Adopción", "goat",
     "Pepa, cabra enana, se comió los geranios de la esquina y se quedó. Es mansa y da compañía. Ideal quinta o terraza reforzada, no balcón de 2 m.",
     None),
    ("Constitución, CABA", 38, "Tránsito animal", "duck",
     "Un pato doméstico cruzó la 9 de Julio. Le decimos Julio. Nada en una palangana y sigue a quien le tira lechuga. El zoológico barrial lo tiene 48 h.",
     None),
    ("Barracas, CABA", 39, "Rescate animal", "hedgehog",
     "Erizo encontrado en un tacho de compost. Le pusimos Púa. Come tenebrios y se enrolla si hay ruido. No es silvestre de acá: alguien lo soltó y ahora busca casa.",
     None),
    ("Parque Patricios, CABA", 41, "Adopción", "pig",
     "Lola, mini pig de 18 kg, no entra más en el depto. Es limpia y gruñe si le cantás. Buscamos casa con patio de tierra, no pileta de plástico.",
     None),
    ("Pompeya, CABA", 43, "Mascotas", "capybara",
     "Un carpincho joven apareció en el Riachuelo y se sentó en la vereda. Prefectura lo llevó a un centro. Mientras tanto, los pibes le dejaron sandía en la reja.",
     None),
    ("Villa Lugano, CABA", 44, "Adopción", "dog",
     "Tano, mestizo de plaza, espera en el CIC. Se lleva bien con chicos y le tiene miedo a los globos. Ideal familia paciente, no departamento de fiestas.",
     None),
    ("Villa Soldati, CABA", 46, "Tránsito animal", "puppy",
     "Cinco cachorros bajo un auto estacionado. La conductora avisó y nos quedamos hasta que arrancó. Ya comieron. Falta desparasitar y encontrar cinco hogares.",
     None),
    ("Villa Riachuelo, CABA", 47, "Adopción", "cat",
     "Doña Rosa, gata de 11 años, se quedó en el merendero cuando cerró el local. Come pollo desmenuzado y se sienta en las sillas. Buscamos casa sin mudanzas.",
     None),
    ("Villa Pueyrredón, CABA", 49, "Rescate animal", "dog",
     "Beto se trabó en una reja. Los bomberos lo sacaron sin un rasguño. Hoy duerme en un living de Mosconi. Dueño no apareció: se publica en el grupo del barrio.",
     None),
    ("Agronomía, CABA", 51, "Mascotas", "rabbit",
     "La facultad recibió un conejo angora que alguien ató a un árbol. Le cortamos los nudos y le cepillamos el pelo. Se llama Algodón y busca tutor que sepa de lana.",
     None),
    ("Villa Ortúzar, CABA", 52, "Adopción", "kitten",
     "Trío de gatitos grises en el cantero de la plaza. La mamá come y se deja tocar. Adoptamos en tándem: no separamos a la camada si se puede evitar.",
     None),
    ("Palermo Hollywood, CABA", 53, "Tránsito animal", "cat",
     "Un siamés cruzado se coló en un ensayo de teatro. Se quedó dormido en el sofá del vestuario. Se llama Telón. 72 h de espera por el dueño y después adopción.",
     None),
    ("Palermo Viejo, CABA", 54, "Adopción", "dog",
     "Rita, galga mestiza, corre poco y se acuesta a los pies. Salió de un predio de Apóstoles. Ideal depto alto: no salta a la calle, mira por la ventana.",
     None),
    ("Las Cañitas, CABA", 56, "Mascotas", "parrot",
     "Cata, cotorra, imita el timbre del edificio. La familia se mudó al exterior y la dejó con la portera. Buscamos voladera o criadero habilitado, no jaula chica.",
     None),
    ("Recoleta, CABA", 57, "Adopción", "cat",
     "Monsieur, gato blanco sordo, vive en la veterinaria de Quintana. Se comunica con la cola. Ideal casa sin balcón abierto: no escucha los autos.",
     None),
    ("Retiro, CABA", 58, "Rescate animal", "dog",
     "Un ovejero se sentó en el andén de Retiro tres tardes seguidas. El personal de estación le puso agua. Hoy está en tránsito en un PH de San Martín.",
     None),
    ("Puerto Madero, CABA", 59, "Tránsito animal", "turtle",
     "Tortuga hallada en un cantero de los diques. No es marina: es de agua dulce. El acuario barrial la tiene hasta que alguien arme un tanque de verdad.",
     None),
    ("Monserrat, CABA", 61, "Adopción", "puppy",
     "Beto Jr., mestizo de dos meses, cabe en una mochila pero no viaja en subte. Vacunas el jueves. Buscamos primer perro para alguien que esté en casa a la siesta.",
     None),
    ("San Nicolás, CABA", 62, "Mascotas", "hamster",
     "Tres hámsteres de un kiosco que cerró. Comen mix y corren de noche. Se adoptan juntos o de a uno, pero no como souvenir de oficina.",
     None),
    ("Balvanera, CABA", 63, "Rescate animal", "cat",
     "Misha se quedó trabada en un entretecho. La bajamos con atún y linterna. Tiene un collar sin chapita. 48 h en el grupo del Once y después se publica adopción.",
     None),
    ("Once, CABA", 64, "Adopción", "dog",
     "Chicho, caniche mestizo sénior, espera en la peluquería canina. Le cortaron nudos y le quedó cara de león. Busca sofá, no plaza de domingo lleno.",
     None),
    ("Abasto, CABA", 66, "Tránsito animal", "guinea",
     "Cuis tricolor encontrado en un pasillo del shopping. Le pusimos Abasto. Come morrón y silba si hay gente. Ideal chico con adultos responsables.",
     None),
    ("Villa del Parque, CABA", 67, "Adopción", "golden",
     "Tomás, golden de 9 años, se quedó ciego de un ojo. Camina el pasillo sin chocar. Una familia lo tuvo 8 años y se mudó al exterior: busca continuidad, no lástima.",
     None),
    ("Villa Santa Rita, CABA", 68, "Mascotas", "duck",
     "Pata doméstica en la plazoleta de Nazca. Los vecinos le armaron un tacho con rampa. No es fauna nativa: alguien la soltó. Buscamos quinta con pileta baja.",
     None),
    ("Floresta, CABA", 69, "Rescate animal", "dog",
     "Lola se escapó de un traslado y apareció en la estación. El guardabarrera le dio galletas. Ya está identificada: el dueño vive a seis cuadras y lloró en el andén.",
     None),
    ("Vélez Sársfield, CABA", 71, "Adopción", "kitten",
     "Nube y Carbón, hermanos de 8 semanas, no se sueltan. El refugio pide adopción doble. Comen papilla y se pelean por un pompón.",
     None),
    ("Monte Castro, CABA", 72, "Tránsito animal", "cat",
     "Gato naranja con un bigote quemado. El vet dice que está bien. Se llama Bigote. Duerme en la caja de la impresora. Buscamos depto sin perros celosos.",
     None),
    ("Villa Real, CABA", 73, "Adopción", "dog",
     "Rocco, boxer mestizo, babea y se ríe. El canil municipal lo tiene listo. Ideal casa con reja baja: salta poco, ladra si pasa el carrito de la verdura.",
     None),
    ("Versalles Oeste, CABA", 74, "Mascotas", "horse",
     "Una yegua pampa pastaba en un baldío. Rural la revisó: no tiene dueño visible. Come fardo donado. Buscamos campo de tránsito, no selfie de plaza.",
     None),
    ("Villa Luro, CABA", 76, "Adopción", "tabby",
     "Fela, gata atigrada de 6 años, espera en un PH. Se lleva con perros chicos. El dueño anterior se internó: la familia pide un hogar que no la devuelva en un mes.",
     None),
    ("Liniers Norte, CABA", 77, "Rescate animal", "puppy",
     "Cachorra atada a un poste con hilo. La cortamos y la llevamos al vet. Se llama Hilo. Come y duerme. Mañana desparasitación; después, adopción con contrato.",
     None),
    ("Mataderos Sur, CABA", 78, "Tránsito animal", "goat",
     "Chivo joven en un baldío de Alberdi. Come yuyo y se deja tocar. No es de faena: es de compañía. El predio vecinal lo tiene 72 h.",
     None),
    ("Villa Soldati Este, CABA", 79, "Adopción", "dog",
     "Cira, mestiza sorda, se comunica con la mano. El entrenador del barrio le enseñó «sentado» con señas. Ideal casa sin calle abierta.",
     None),
    ("Parque Avellaneda, CABA", 81, "Mascotas", "rabbit",
     "Conejo negro suelto en el parque. Lo atrapamos con lechuga. Se llama Sombra. Dientes largos: hay que llevarlo al vet exótico. Buscamos tutor que sepa eso.",
     None),
    ("Villa General Mitre, CABA", 82, "Adopción", "cat",
     "Pepa, gata calico, vive en la peluquería. Se sube a las sillas y no se va. La dueña se jubila. Buscamos casa con ventanas con red.",
     None),
    ("Paternal Norte, CABA", 83, "Rescate animal", "dog",
     "Un cruza galgo se desmayó de calor en la 24. Lo mojamos y lo llevaron al hospital. Hoy bebe solo. Se llama Sombra también: hay que ponerle chapita.",
     None),
    ("Chacarita Sur, CABA", 84, "Tránsito animal", "parrot",
     "Loro hablador en un árbol de Guzmán. Dice el nombre de una nena. Publicamos el audio en el grupo. Si no aparece dueño, va a un criadero habilitado.",
     None),
    ("Colegiales Este, CABA", 86, "Adopción", "puppy",
     "Mora Jr., mestiza de 10 semanas, ya sabe dónde está el diario. El refugio pide familia con patio o terrazas cerradas. No es un perro de 8 h sola.",
     None),
    ("Belgrano R, CABA", 87, "Mascotas", "hedgehog",
     "Erizo africano dejado en una caja en el veterinario. Come pienso especial. No es de suelta en plaza: se muere de frío. Buscamos tutor informado.",
     None),
    ("Núñez Río, CABA", 88, "Adopción", "golden",
     "Greta, golden de 4 años, se quedó sin familia por alergia de un nene. Es mansa y se moja las patas en el bebedero. El club de remo la pasea hasta que haya casa.",
     None),
    ("Saavedra Parque, CABA", 89, "Tránsito animal", "kitten",
     "Gatito blanco en el motor de un auto. El dueño del auto avisó antes de arrancar. Se llama Radiador. Cabe en una mano. Leche de reemplazo cada 4 h.",
     None),
    ("Coghlan Este, CABA", 91, "Rescate animal", "dog",
     "Toby se tragó un hilo. Operación de 40 minutos y ya come pollo. El dueño no tiene para la cuenta: el barrio juntó el resto. Hoy duerme en casa, no en jaula.",
     None),
    ("Villa Urquiza Norte, CABA", 92, "Adopción", "cat",
     "Sombra, gata negra de 3 años, espera en el consultorio. Le dicen que da mala suerte: nosotros decimos que da siesta. Buscamos alguien sin supersticiones.",
     None),
    ("Devoto Norte, CABA", 93, "Mascotas", "guinea",
     "Cuis pelado de laboratorio que un alumno trajo a casa. Es rosa y come heno. No es un juguete de feria. El club de ciencias busca familia que entienda eso.",
     None),
    ("Villa Pueyrredón Este, CABA", 94, "Tránsito animal", "ferret",
     "Hurón escapado de un balcón. Lo atrapamos con un trapo. Se llama Cinta. Vacunas al día según el chip. Dueño avisado: se reencuentran esta tarde.",
     None),
    ("Villa Ortúzar Sur, CABA", 96, "Adopción", "dog",
     "Pancho, mestizo de 5 años, espera en el canil de la sociedad de fomento. Se lleva con gatos. Ideal PH con patio interno.",
     None),
    ("Palermo Botanico, CABA", 97, "Rescate animal", "duck",
     "Pato herido en el lago. Guardaparques lo sacó y lo llevaron a un centro. Come arvejas. No es mascota de bañadera: cuando sane, vuelve al agua grande.",
     None),
    ("Palermo Soho Sur, CABA", 98, "Adopción", "tabby",
     "Lino, gato atigrado, se quedó en un Airbnb. Los huéspedes se fueron. La portera lo alimenta. Buscamos adopción con contrato, no «mientras tanto».",
     None),
    ("Villa Crespo Norte, CABA", 99, "Mascotas", "chinchilla",
     "Chinchilla en una jaula chica dejada en la vereda. Ya tiene baño de arena y una jaula más alta. Se llama Polvo. Buscamos tutor que no la bañe con agua.",
     None),
    ("Almagro Sur, CABA", 101, "Tránsito animal", "puppy",
     "Cachorro con un ojito lloroso. El vet dice que es conjuntivitis, no ceguera. Se llama Guiño. Tres días de gotas y después adopción.",
     None),
    ("Caballito Norte, CABA", 102, "Adopción", "dog",
     "Emma, labradora mestiza, espera en el club. Nada en la pileta de lona. Ideal familia que camine de mañana, no que la deje 10 h.",
     None),
    ("Flores Sur, CABA", 103, "Rescate animal", "cat",
     "Gato atascado en un árbol de Rivadavia. Bomberos lo bajaron. No tiene chip. 24 h en el grupo y después se publica como adopción.",
     None),
    ("Floresta Norte, CABA", 104, "Adopción", "kitten",
     "Miel, gatita canela, cabe en un tazón. Come y ronronea. El refugio pide que no se separe de su hermano Tostada si se puede.",
     None),
    ("Monte Castro Este, CABA", 106, "Mascotas", "turtle",
     "Tortuga terrestre en un cantero. No es de suelta: es de terrario seco. El club de reptiles la tiene. Buscamos adulto, no regalo de cumpleaños.",
     None),
    ("Versalles Sur, CABA", 107, "Adopción", "donkey",
     "Burro joven en un predio de la General Paz. Come y se deja tocar las orejas. Una ONG rural busca campo a menos de 80 km.",
     None),
    ("Mataderos Norte, CABA", 108, "Tránsito animal", "pig",
     "Chancho vietnamita en un baldío. No es de faena familiar: es mascota que gruñe. El predio vecinal lo tiene hasta el domingo.",
     None),
    ("Liniers Sur, CABA", 109, "Adopción", "goat",
     "Cabra con un cencerro. Se llama Campana. Come yuyo y se sube a las sillas. Ideal quinta, no terraza de 4 m.",
     None),
    ("Villa Luro Este, CABA", 111, "Rescate animal", "dog",
     "Perro atropellado leve en Rivadavia. El conductor se bajó y pagó la radiografía. No tiene dueño. Hoy cojea poco. Se llama Rivadavia, mal nombre, buen final.",
     None),
    ("Villa Real Norte, CABA", 112, "Adopción", "cat",
     "Tita, gata sénior, espera en la veterinaria. Come blando. Ideal persona mayor que quiera compañía quieta.",
     None),
    ("Villa Devoto Sur, CABA", 113, "Mascotas", "horse",
     "Poni dejado en un baldío. Come y ya no tiene llagas. El club hípico le presta box. Buscamos padrino para el fardo, no jinete de fin de semana.",
     None),
    ("Villa Urquiza Sur, CABA", 114, "Tránsito animal", "rabbit",
     "Conejo enano en una plaza. Lo atrapamos con perejil. Se llama Perejil. Dientes: control en 10 días. Buscamos tutor de exóticos.",
     None),
    ("Saavedra Este, CABA", 116, "Adopción", "puppy",
     "Luna Jr., mestiza blanca, ya sabe sentarse. El refugio pide familia con otro perro manso o con tiempo. No es un perro de 9 a 18 fuera.",
     None),
    ("Núñez Norte, CABA", 117, "Rescate animal", "dog",
     "Un cruza collie se perdió en la costanera. El dueño publicó foto y a las dos horas lo tenían en el parrilla. Se abrazaron. Chapita nueva esta semana.",
     None),
    ("Belgrano C, CABA", 118, "Adopción", "golden",
     "Max, golden de 6 años, se quedó sin patio. El dueño pide adopción responsable con jardín. Es un perro de agua: si hay pileta, mejor.",
     None),
    ("Colegiales Oeste, CABA", 119, "Mascotas", "parrot",
     "Agapornis en pareja, dejados en una jaula en el chino. Comen alpiste y se acicalan. Se adoptan juntos. No son decoración de living.",
     None),
    ("Chacarita Norte, CABA", 121, "Tránsito animal", "kitten",
     "Gatito en un contenedor. Lo sacamos con guantes. Come y ya no tiembla. Se llama Contenedor, vamos a cambiarle el nombre cuando haya casa.",
     None),
    ("Villa Crespo Sur, CABA", 122, "Adopción", "tabby",
     "Rita, gata atigrada de 2 años, espera en un PH. Se lleva con perros. El dueño se va a estudiar. Buscamos continuidad, no «prueba de 15 días».",
     None),
    ("Palermo Norte, CABA", 123, "Rescate animal", "cat",
     "Gato en un conducto de aire. El técnico lo sacó y se quedó en la oficina. Se llama Split. 48 h de aviso y después adopción interna del edificio.",
     None),
    ("Recoleta Sur, CABA", 124, "Adopción", "dog",
     "Caniche toy sénior, se llama Monsieur también. Come blando y se sube a la falda. Ideal persona que no viaje cada mes.",
     None),
    ("San Telmo Norte, CABA", 126, "Mascotas", "capybara",
     "Carpincho de peluche no: uno de verdad se asomó en el Riachuelo otra vez. No se toca. Prefectura lo observó y se fue nadando. Historia tierna, no mascota.",
     None),
    ("La Boca Norte, CABA", 127, "Adopción", "puppy",
     "Caminito, mestizo color óxido, espera en el club. Se lleva con gatos. Ideal casa con reja, no puerto de turistas.",
     None),
    ("Barracas Sur, CABA", 128, "Tránsito animal", "dog",
     "Perra preñada en un baldío. La llevamos al vet: tres cachorros en camino. Tránsito largo. Buscamos casa para la mamá primero, los pibes después.",
     None),
    ("Parque Patricios Norte, CABA", 129, "Adopción", "cat",
     "Gol, gato del club, se quedó cuando mudaron la sede. Come y se sienta en el banco. Buscamos socio que lo lleve a un depto, no a la cancha.",
     None),
    ("Boedo Norte, CABA", 131, "Rescate animal", "dog",
     "Un mestizo se quedó dormido en el umbral de la pizzería. Le dieron masa cruda (mal) y agua (bien). Hoy está en tránsito. Se llama Muzza, por supuesto.",
     None),
    ("Almagro Norte, CABA", 132, "Adopción", "kitten",
     "Tres gatitos en una caja en el subte B. El guardia los bajó en Carlos Gardel. Ya comieron. El refugio los tiene: adopción con desparasitación.",
     None),
    ("Caballito Sur, CABA", 133, "Mascotas", "hamster",
     "Hámster ruso escapado de una jaula de feria. Lo encontramos en un placard. Se llama Placard. Buscamos jaula de dos pisos, no rueda chica.",
     None),
    ("Flores Norte, CABA", 134, "Adopción", "dog",
     "Canela, mestiza de 8 años, espera en el CIC. Se lleva con chicos grandes. No es un perro de correa corta: es un perro de vereda lenta.",
     None),
    ("Villa del Parque Sur, CABA", 136, "Tránsito animal", "rabbit",
     "Conejo manchado en el cantero de la estación. Lo atrapamos con cilantro. Se llama Andén. Control de dientes el lunes.",
     None),
    ("Agronomía Sur, CABA", 137, "Adopción", "cat",
     "Decano, gato de la facultad, se jubiló con el edificio. Come en el bar. Un docente se lo lleva a casa el viernes si nadie del claustro se anota.",
     None),
    ("Villa Ortúzar Norte, CABA", 138, "Rescate animal", "puppy",
     "Cachorro en una bolsa (la sacamos). Come y ya no llora. Se llama Bolsa, vamos a pedirle un nombre lindo a quien lo adopte.",
     None),
    ("Paternal Sur, CABA", 139, "Adopción", "golden",
     "Lola Golden, de 3 años, se quedó sin patio. El club de fútbol la pasea. Ideal casa con jardín y gente que vuelva a la hora de comer.",
     None),
    ("Chacarita Oeste, CABA", 141, "Mascotas", "ferret",
     "Hurón en un caño de gas en desuso. Lo sacamos con un trapo. Vacunas pendientes. El vet exótico lo tiene 24 h.",
     None),
    ("Villa Crespo Oeste, CABA", 142, "Adopción", "tabby",
     "Mora atigrada, 5 años, espera en un PH. Se lleva con perros chicos. El dueño se internó: la hermana pide un hogar que mande fotos.",
     None),
    ("Palermo Este, CABA", 143, "Tránsito animal", "cat",
     "Gato en un árbol de Plaza Italia 6 horas. Bomberos lo bajaron. Chip de un depto de Gurruchaga. Dueña avisada: se reencuentran esta noche.",
     None),
    ("Belgrano Sur, CABA", 144, "Adopción", "dog",
     "Otto, schnauzer mestizo, espera en la peluquería. Le cortaron la barba. Ideal persona que cepille, no que lo deje enredado.",
     None),
    ("Núñez Sur, CABA", 146, "Rescate animal", "puppy",
     "Cachorros en una caja en el tren. El guarda los bajó en Núñez. Ya comieron. El refugio del Bajo los tiene: cinco hogares, no uno para todos.",
     None),
    ("Saavedra Oeste, CABA", 147, "Adopción", "kitten",
     "Pimienta, gatita negra, cabe en una taza. El merendero la alimentó una semana. Buscamos casa con ventanas con red.",
     None),
    ("Villa Urquiza Este, CABA", 148, "Mascotas", "guinea",
     "Cuis largo-pelo dejado en una plaza. Lo cepillamos. Se llama Bufanda. Buscamos tutor que sepa que no es un hámster.",
     None),
    ("Coghlan Oeste, CABA", 149, "Tránsito animal", "dog",
     "Perro con un hueso atorado. El vet lo sacó. Dueño no aparece. 48 h y se publica adopción. Se llama Hueso, mal nombre otra vez.",
     None),
    ("Villa Pueyrredón Oeste, CABA", 151, "Adopción", "cat",
     "Nube sénior, gata blanca, espera en el consultorio. Come blando. Ideal casa sin otros gatos territoriales.",
     None),
    ("Devoto Este, CABA", 152, "Rescate animal", "dog",
     "Mestizo en una zanja después de la lluvia. Lo sacamos con una sábana. Come y ya no tiembla. Se llama Zanja. Chapita nueva el martes.",
     None),
    ("Villa Real Sur, CABA", 153, "Adopción", "puppy",
     "Ciro, mestizo de 3 meses, ya sabe dónde está el agua. El CIC pide familia con tiempo de siesta. No es un perro de 10 h sola.",
     None),
    ("Versalles Norte, CABA", 154, "Mascotas", "donkey",
     "Burra con un lazo flojo en un baldío. Se lo sacamos. Come y se deja cepillar. ONG rural busca campo. No es selfie de ruta.",
     None),
    ("Mataderos Este, CABA", 156, "Adopción", "goat",
     "Chiva enana, se llama Mota. Come yuyo y se sube a los cajones. Ideal quinta con alambrado, no terraza de amigos.",
     None),
    ("Liniers Este, CABA", 157, "Tránsito animal", "horse",
     "Caballo flaco en la General Paz. Rural lo revisó. Come avena. El club le presta box 5 días. Buscamos padrino de fardo.",
     None),
    ("Villa Luro Oeste, CABA", 158, "Adopción", "dog",
     "Pancha, mestiza de 9 años, espera en el CIC. Se lleva con gatos. Ideal persona que camine lento, no que corra maratones.",
     None),
    ("Floresta Sur, CABA", 159, "Rescate animal", "cat",
     "Gato en un tanque de agua vacío. Lo sacamos con una soga y un trapo. Come. Se llama Tanque. 24 h en el grupo del barrio.",
     None),
    ("Monte Castro Oeste, CABA", 161, "Adopción", "tabby",
     "Fito, gato atigrado, espera en la veterinaria. Se lleva con perros. El dueño se mudó a un monoambiente. Buscamos PH.",
     None),
    ("Villa Soldati Oeste, CABA", 162, "Mascotas", "duck",
     "Pata con un alerón lastimado. El vet la vendó. Come lechuga. Cuando vuele corto, vuelve a un predio con agua, no a una bañadera.",
     None),
    ("Villa Riachuelo Norte, CABA", 163, "Tránsito animal", "turtle",
     "Tortuga en una palangana en la vereda. No es de paseo: es de tanque. El club de acuarios la tiene. Buscamos adulto responsable.",
     None),
    ("Pompeya Norte, CABA", 164, "Adopción", "dog",
     "Rulo, mestizo rizado, espera en el club. Se lleva con chicos. Ideal casa con patio de tierra, no depto de vidrio.",
     None),
    ("Boedo Sur, CABA", 166, "Rescate animal", "puppy",
     "Cachorro en un cajón de tomates. Come y ya no llora. Se llama Tomate. El refugio lo tiene: adopción el sábado con contrato.",
     None),
    ("San Telmo Sur, CABA", 167, "Adopción", "cat",
     "Tango, gato negro, vive en un café. La dueña se jubila. Buscamos casa con siesta, no local nuevo con gente todo el día.",
     None),
    ("Constitución Norte, CABA", 168, "Mascotas", "pig",
     "Mini pig en un baldío. Come y gruñe si le cantás. El predio lo tiene hasta el lunes. Ideal quinta, no baño de depto.",
     None),
    ("Monserrat Sur, CABA", 169, "Tránsito animal", "chinchilla",
     "Chinchilla en una mochila olvidada en el subte A. Come y se baña en arena. Si no aparece dueño, va a un tutor de exóticos.",
     None),
    ("Puerto Madero Norte, CABA", 171, "Adopción", "golden",
     "Dique, golden de 2 años, se quedó sin terraza. El club de remo lo pasea. Ideal casa con jardín y gente que vuelva a comer.",
     None),
    ("Retiro Norte, CABA", 172, "Rescate animal", "dog",
     "Perro en el andén otra vez, pero este tenía chapita. El dueño vino en 20 minutos. Historia corta y buena: las chapitas sirven.",
     None),
    ("Recoleta Norte, CABA", 173, "Adopción", "kitten",
     "Dos gatitos en una jardinera de Quintana. La portera los alimentó. El refugio los tiene: adopción doble si se puede.",
     None),
    ("Palermo Hollywood Norte, CABA", 174, "Mascotas", "parrot",
     "Cacatúa que imita el WhatsApp. La familia se mudó. Buscamos criadero habilitado. No es un juguete de living con eco.",
     None),
    ("Las Cañitas Sur, CABA", 176, "Tránsito animal", "cat",
     "Gato en el techo de un taxi. El taxista avisó y esperó. Dueña a tres cuadras. Se reencontraron en el semáforo. Chapita nueva.",
     None),
    ("Belgrano Norte, CABA", 177, "Adopción", "dog",
     "Luna sénior, mestiza, espera en el club. Come blando. Ideal persona que no viaje cada quince días.",
     None),
    ("Núñez Este, CABA", 178, "Rescate animal", "hedgehog",
     "Erizo en un tacho de hojas. No es nativo de acá. El vet exótico lo tiene. Buscamos tutor que no lo suelte en la plaza.",
     None),
    ("Saavedra Norte, CABA", 179, "Adopción", "puppy",
     "Ciro Jr., mestizo de 9 semanas, ya sabe dónde está el agua. El CIC pide familia con tiempo. No es un perro de oficina todo el día.",
     None),
    ("Villa Urquiza Oeste, CABA", 181, "Mascotas", "rabbit",
     "Coneja en una caja de zapatos en la estación. Come heno. Se llama Andén Jr. Control de dientes. Tutor de exóticos, no regalo.",
     None),
    ("Villa Ortúzar Este, CABA", 182, "Tránsito animal", "guinea",
     "Dos cuises en una mochila olvidada. Comen y silban. Si no aparece dueño, se adoptan juntos.",
     None),
    ("Paternal Este, CABA", 183, "Adopción", "cat",
     "Manchita, gata con un ojo azul, espera en la veterinaria. Se lleva con perros. Ideal PH con red en las ventanas.",
     None),
    ("Agronomía Norte, CABA", 184, "Rescate animal", "dog",
     "Mestizo en el predio de la facultad. Los estudiantes le pusieron Decano Jr. Come y espera. El club de veterinaria busca casa.",
     None),
    ("Villa del Parque Norte, CABA", 186, "Adopción", "tabby",
     "Lino Jr., atigrado de 1 año, espera en un PH. Se lleva con gatos. El dueño se va a otra provincia. Buscamos continuidad.",
     None),
    ("Villa Devoto Oeste, CABA", 187, "Mascotas", "ferret",
     "Hurón en un caño de desagüe otra vez. Esta vez tenía arnés. Dueña a una cuadra. Se reencontraron. Historia corta: el arnés también sirve.",
     None),
    ("Villa Pueyrredón Norte, CABA", 188, "Adopción", "dog",
     "Tito, mestizo de 4 años, espera en el CIC. Se lleva con chicos. Ideal casa con reja, no balcón de 9º.",
     None),
    ("Coghlan Norte, CABA", 189, "Tránsito animal", "kitten",
     "Gatito en el motor, otra vez. El auto no arrancó porque el dueño miró. Se llama Radiador Jr. Leche de reemplazo. Casa esta semana.",
     None),
    ("Colegiales Norte, CABA", 191, "Adopción", "golden",
     "Sol, golden de 7 años, se quedó sin familia por un viaje. Camina despacio. El club la pasea. Ideal sofá, no plaza llena.",
     None),
    ("Chacarita Este, CABA", 192, "Rescate animal", "puppy",
     "Cachorros en una caja en el cementerio. El guardia avisó. Ya comieron. El refugio los tiene: nombres nuevos, no «Cementerio».",
     None),
    ("Villa Crespo Este, CABA", 193, "Adopción", "cat",
     "Gris, gato de 8 años, espera en la peluquería. Se sube a las sillas. La dueña se muda. Buscamos casa con siesta.",
     None),
    ("Palermo Sur, CABA", 194, "Mascotas", "turtle",
     "Tortuga en una fuente. No es adorno: es un animal de 30 años. El acuario barrial la tiene. Buscamos tanque, no palangana.",
     None),
    ("Caballito Este, CABA", 196, "Tránsito animal", "dog",
     "Perra en el andén de Primera Junta. Chapita de un depto de Acoyte. Dueña en 15 minutos. Otra vez: las chapitas sirven.",
     None),
    ("Almagro Este, CABA", 197, "Adopción", "puppy",
     "Nube Jr., mestiza blanca, espera en el refugio. Ya sabe sentarse. Familia con tiempo, no con 10 h de oficina.",
     None),
    ("Boedo Este, CABA", 198, "Rescate animal", "cat",
     "Gato en un árbol 8 horas. Vecinos le pusieron atún en el tronco. Bajó solo. Dueño no aparece. 24 h y adopción.",
     None),
    ("San Nicolás Norte, CABA", 199, "Adopción", "dog",
     "Coco sénior, mestizo, espera en la veterinaria. Come blando. Ideal persona que quiera compañía quieta y no un perro de trote.",
     None),
    ("Monserrat Norte, CABA", 201, "Mascotas", "hamster",
     "Hámster en una rueda chica dejada en un kiosco. Ya tiene jaula de dos pisos. Se llama Rueda. Tutor que no lo saque a pasear en la mano por la calle.",
     None),
    ("Balvanera Norte, CABA", 202, "Tránsito animal", "kitten",
     "Gatitos en un cajón de verdura en el Once. El puestero avisó. Ya comieron. El refugio los tiene: adopción con vacunas.",
     None),
    ("Once Sur, CABA", 203, "Adopción", "tabby",
     "Mora de Once, atigrada, espera en el consultorio. Se lleva con perros. Ideal PH, no local con gente todo el día.",
     None),
    ("Abasto Norte, CABA", 204, "Rescate animal", "dog",
     "Mestizo dormido en la puerta del shopping. Seguridad le puso agua. Hoy está en tránsito. Se llama Abasto Jr. Chapita el jueves.",
     None),
    ("Villa Santa Rita Norte, CABA", 206, "Adopción", "cat",
     "Pepa Jr., gata calico, espera en un PH. Se lleva con gatos. El dueño se internó. La hermana pide fotos cada tanto.",
     None),
    ("Villa General Mitre Norte, CABA", 207, "Mascotas", "rabbit",
     "Conejo angora otra vez, este en una plaza chica. Cepillado hecho. Se llama Lana. Tutor que sepa de nudos, no de selfie.",
     None),
    ("Villa Soldati Norte, CABA", 208, "Adopción", "dog",
     "Tano Jr., mestizo de plaza, espera en el CIC. Se lleva con chicos. Ideal familia paciente, no departamento de fiestas.",
     None),
    ("Villa Lugano Norte, CABA", 209, "Tránsito animal", "puppy",
     "Cachorros bajo un auto, otra cuadra. La conductora esperó. Ya comieron. Faltan hogares. El sábado, castración de la mamá.",
     None),
    ("Mataderos Oeste, CABA", 211, "Adopción", "golden",
     "Olivia Jr., golden de 11 años, camina despacio. El club la pasea. No es un perro de corrida: es un perro de siesta. Casa con sofá.",
     None),
    ("Liniers Oeste, CABA", 212, "Rescate animal", "dog",
     "Pastor mestizo en la plaza, se sentó y no se fue. Agua y hall del edificio. Se llama Simón Jr. Dueño no aparece: adopción la semana que viene.",
     None),
]

STORIES = STORIES[:100]
assert len(STORIES) == 100, len(STORIES)

def esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')

lines = [
    "package com.onlygoodthings.shared.data.local",
    "",
    "import com.onlygoodthings.shared.domain.AuthorKind",
    "import com.onlygoodthings.shared.domain.MediaKind",
    "import com.onlygoodthings.shared.domain.PostPersonRole",
    "",
    "/** 100 historias tiernas de mascotas. sourceUrl solo si hay nota real; si no, foto Commons del tipo. */",
    "internal object OgtPetNewsSeed {",
    "    data class PetStory(",
    "        val id: String,",
    "        val author: String,",
    "        val place: String,",
    "        val hoursAgo: Double,",
    "        val tag: String,",
    "        val body: String,",
    "        val sourceUrl: String?,",
    "        val photo: String,",
    "        val impact: Int,",
    "    )",
    "",
    "    val items: List<PetStory> = listOf(",
]

for i, (place, hours, tag, photo, body, url) in enumerate(STORIES, start=1):
    author = AUTHORS[(i - 1) % len(AUTHORS)]
    sid = f"pet-{i:03d}"
    src = "null" if not url else f'"{esc(url)}"'
    impact = 40 + (i * 7) % 160
    lines.append(
        f'        PetStory("{sid}", {author}, "{esc(place)}", {hours}.0, "{tag}", "{esc(body)}", {src}, "seed_pet_{photo}", {impact}),'
    )

lines += [
    "    )",
    "",
    "    fun append(db: OgtLocalDatabase, now: Long) {",
    "        items.forEachIndexed { index, item ->",
    "            val post = LocalSocialPost(",
    "                id = item.id,",
    "                authorKind = AuthorKind.USER,",
    "                authorUserId = item.author,",
    "                authorCompanyId = null,",
    "                place = item.place,",
    "                timeLabel = timeLabel(item.hoursAgo),",
    "                tag = item.tag,",
    "                body = item.body,",
    "                impactCount = item.impact,",
    "                commentCount = 1 + index % 4,",
    "                isStory = false,",
    "                storyLabel = null,",
    "                createdAtEpochMs = now - (item.hoursAgo * 3_600_000).toLong(),",
    "                sourceUrl = item.sourceUrl,",
    "            )",
    "            db.posts += post",
    "            db.postPeople += LocalPostPerson(item.id, item.author, PostPersonRole.AUTHOR)",
    "            db.postPeople += LocalPostPerson(item.id, item.author, PostPersonRole.PROTAGONIST)",
    "            db.postMedia += LocalPostMedia(",
    "                id = \"${item.id}-img\",",
    "                postId = item.id,",
    "                kind = MediaKind.IMAGE,",
    "                url = \"asset://${item.photo}\",",
    "                sortOrder = 0,",
    "                assetKey = item.photo,",
    "                altText = item.tag,",
    "            )",
    "        }",
    "    }",
    "",
    "    private fun timeLabel(hoursAgo: Double): String = when {",
    "        hoursAgo < 1 -> \"Hace ${(hoursAgo * 60).toInt()} min\"",
    "        hoursAgo < 24 -> \"Hace ${hoursAgo.toInt()} h\"",
    "        hoursAgo < 48 -> \"Ayer\"",
    "        else -> \"Hace ${(hoursAgo / 24).toInt()} d\"",
    "    }",
    "}",
    "",
]
OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(STORIES)} stories -> {OUT}")
